@echo off
SET THISNAME=iedup
REM installutil %THISNAME%.exe
SET THIS_PATH=%~dp0
SET UNINSTALL_PATH=%THIS_PATH%\bin\Debug\%THISNAME%.exe
IF EXIST "%PROGRAMFILES%\%THISNAME%\%THISNAME%.exe" "%PROGRAMFILES%\%THISNAME%\%THISNAME%.exe"  -uninstall
"%UNINSTALL_PATH%" -uninstall
IF EXIST "%THIS_PATH%\bin\Release\%THISNAME%.exe" UNINSTALL_PATH=%THIS_PATH%\bin\Release\%THISNAME%.exe
"%UNINSTALL_PATH%" -uninstall
pause